version: '3'
services:
  pgsql:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=TEST://:9092,INSIDE://:9093
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=TEST:PLAINTEXT,INSIDE:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=TEST://127.0.0.1:9092,INSIDE://kafka:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - '2181:2181'

  kowl:
    image: quay.io/cloudhut/kowl:master
    ports:
      - '8080:8080'
    environment:
      - KAFKA_BROKERS=kafka:9093

  redis:
    image: redis:6.2
    ports:
      - '6379:6379'
