// Code generated by entc, DO NOT EDIT.

package orderlineitem

import (
	"time"
)

const (
	// Label holds the string label denoting the orderlineitem type in the database.
	Label = "order_line_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrderID holds the string denoting the order_id field in the database.
	FieldOrderID = "order_id"
	// FieldProductID holds the string denoting the product_id field in the database.
	FieldProductID = "product_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// Table holds the table name of the orderlineitem in the database.
	Table = "order_line_items"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "order_line_items"
	// OwnerInverseTable is the table name for the Order entity.
	// It exists in this package in order to avoid circular dependency with the "order" package.
	OwnerInverseTable = "orders"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "order_order_items"
)

// Columns holds all SQL columns for orderlineitem fields.
var Columns = []string{
	FieldID,
	FieldOrderID,
	FieldProductID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "order_line_items"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"order_order_items",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
