// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pot-code/go-cqrs-demo/ent/order"
	"github.com/pot-code/go-cqrs-demo/ent/orderlineitem"
)

// OrderLineItemCreate is the builder for creating a OrderLineItem entity.
type OrderLineItemCreate struct {
	config
	mutation *OrderLineItemMutation
	hooks    []Hook
}

// SetOrderID sets the "order_id" field.
func (olic *OrderLineItemCreate) SetOrderID(s string) *OrderLineItemCreate {
	olic.mutation.SetOrderID(s)
	return olic
}

// SetProductID sets the "product_id" field.
func (olic *OrderLineItemCreate) SetProductID(s string) *OrderLineItemCreate {
	olic.mutation.SetProductID(s)
	return olic
}

// SetCreatedAt sets the "created_at" field.
func (olic *OrderLineItemCreate) SetCreatedAt(t time.Time) *OrderLineItemCreate {
	olic.mutation.SetCreatedAt(t)
	return olic
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (olic *OrderLineItemCreate) SetNillableCreatedAt(t *time.Time) *OrderLineItemCreate {
	if t != nil {
		olic.SetCreatedAt(*t)
	}
	return olic
}

// SetUpdatedAt sets the "updated_at" field.
func (olic *OrderLineItemCreate) SetUpdatedAt(t time.Time) *OrderLineItemCreate {
	olic.mutation.SetUpdatedAt(t)
	return olic
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (olic *OrderLineItemCreate) SetNillableUpdatedAt(t *time.Time) *OrderLineItemCreate {
	if t != nil {
		olic.SetUpdatedAt(*t)
	}
	return olic
}

// SetID sets the "id" field.
func (olic *OrderLineItemCreate) SetID(s string) *OrderLineItemCreate {
	olic.mutation.SetID(s)
	return olic
}

// SetOwnerID sets the "owner" edge to the Order entity by ID.
func (olic *OrderLineItemCreate) SetOwnerID(id string) *OrderLineItemCreate {
	olic.mutation.SetOwnerID(id)
	return olic
}

// SetNillableOwnerID sets the "owner" edge to the Order entity by ID if the given value is not nil.
func (olic *OrderLineItemCreate) SetNillableOwnerID(id *string) *OrderLineItemCreate {
	if id != nil {
		olic = olic.SetOwnerID(*id)
	}
	return olic
}

// SetOwner sets the "owner" edge to the Order entity.
func (olic *OrderLineItemCreate) SetOwner(o *Order) *OrderLineItemCreate {
	return olic.SetOwnerID(o.ID)
}

// Mutation returns the OrderLineItemMutation object of the builder.
func (olic *OrderLineItemCreate) Mutation() *OrderLineItemMutation {
	return olic.mutation
}

// Save creates the OrderLineItem in the database.
func (olic *OrderLineItemCreate) Save(ctx context.Context) (*OrderLineItem, error) {
	var (
		err  error
		node *OrderLineItem
	)
	olic.defaults()
	if len(olic.hooks) == 0 {
		if err = olic.check(); err != nil {
			return nil, err
		}
		node, err = olic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OrderLineItemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = olic.check(); err != nil {
				return nil, err
			}
			olic.mutation = mutation
			if node, err = olic.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(olic.hooks) - 1; i >= 0; i-- {
			if olic.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = olic.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, olic.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (olic *OrderLineItemCreate) SaveX(ctx context.Context) *OrderLineItem {
	v, err := olic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (olic *OrderLineItemCreate) Exec(ctx context.Context) error {
	_, err := olic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (olic *OrderLineItemCreate) ExecX(ctx context.Context) {
	if err := olic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (olic *OrderLineItemCreate) defaults() {
	if _, ok := olic.mutation.CreatedAt(); !ok {
		v := orderlineitem.DefaultCreatedAt()
		olic.mutation.SetCreatedAt(v)
	}
	if _, ok := olic.mutation.UpdatedAt(); !ok {
		v := orderlineitem.DefaultUpdatedAt()
		olic.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (olic *OrderLineItemCreate) check() error {
	if _, ok := olic.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "order_id"`)}
	}
	if _, ok := olic.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "product_id"`)}
	}
	if _, ok := olic.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "created_at"`)}
	}
	if _, ok := olic.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "updated_at"`)}
	}
	return nil
}

func (olic *OrderLineItemCreate) sqlSave(ctx context.Context) (*OrderLineItem, error) {
	_node, _spec := olic.createSpec()
	if err := sqlgraph.CreateNode(ctx, olic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		_node.ID = _spec.ID.Value.(string)
	}
	return _node, nil
}

func (olic *OrderLineItemCreate) createSpec() (*OrderLineItem, *sqlgraph.CreateSpec) {
	var (
		_node = &OrderLineItem{config: olic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: orderlineitem.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: orderlineitem.FieldID,
			},
		}
	)
	if id, ok := olic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := olic.mutation.OrderID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: orderlineitem.FieldOrderID,
		})
		_node.OrderID = value
	}
	if value, ok := olic.mutation.ProductID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: orderlineitem.FieldProductID,
		})
		_node.ProductID = value
	}
	if value, ok := olic.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: orderlineitem.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := olic.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: orderlineitem.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if nodes := olic.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderlineitem.OwnerTable,
			Columns: []string{orderlineitem.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: order.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.order_order_items = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrderLineItemCreateBulk is the builder for creating many OrderLineItem entities in bulk.
type OrderLineItemCreateBulk struct {
	config
	builders []*OrderLineItemCreate
}

// Save creates the OrderLineItem entities in the database.
func (olicb *OrderLineItemCreateBulk) Save(ctx context.Context) ([]*OrderLineItem, error) {
	specs := make([]*sqlgraph.CreateSpec, len(olicb.builders))
	nodes := make([]*OrderLineItem, len(olicb.builders))
	mutators := make([]Mutator, len(olicb.builders))
	for i := range olicb.builders {
		func(i int, root context.Context) {
			builder := olicb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrderLineItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, olicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, olicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, olicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (olicb *OrderLineItemCreateBulk) SaveX(ctx context.Context) []*OrderLineItem {
	v, err := olicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (olicb *OrderLineItemCreateBulk) Exec(ctx context.Context) error {
	_, err := olicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (olicb *OrderLineItemCreateBulk) ExecX(ctx context.Context) {
	if err := olicb.Exec(ctx); err != nil {
		panic(err)
	}
}
