// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/pot-code/go-cqrs-demo/ent/order"
	"github.com/pot-code/go-cqrs-demo/ent/orderlineitem"
	"github.com/pot-code/go-cqrs-demo/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescCreatedAt is the schema descriptor for created_at field.
	orderDescCreatedAt := orderFields[5].Descriptor()
	// order.DefaultCreatedAt holds the default value on creation for the created_at field.
	order.DefaultCreatedAt = orderDescCreatedAt.Default.(func() time.Time)
	// orderDescUpdatedAt is the schema descriptor for updated_at field.
	orderDescUpdatedAt := orderFields[6].Descriptor()
	// order.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	order.DefaultUpdatedAt = orderDescUpdatedAt.Default.(func() time.Time)
	// order.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	order.UpdateDefaultUpdatedAt = orderDescUpdatedAt.UpdateDefault.(func() time.Time)
	orderlineitemFields := schema.OrderLineItem{}.Fields()
	_ = orderlineitemFields
	// orderlineitemDescCreatedAt is the schema descriptor for created_at field.
	orderlineitemDescCreatedAt := orderlineitemFields[3].Descriptor()
	// orderlineitem.DefaultCreatedAt holds the default value on creation for the created_at field.
	orderlineitem.DefaultCreatedAt = orderlineitemDescCreatedAt.Default.(func() time.Time)
	// orderlineitemDescUpdatedAt is the schema descriptor for updated_at field.
	orderlineitemDescUpdatedAt := orderlineitemFields[4].Descriptor()
	// orderlineitem.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	orderlineitem.DefaultUpdatedAt = orderlineitemDescUpdatedAt.Default.(func() time.Time)
	// orderlineitem.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	orderlineitem.UpdateDefaultUpdatedAt = orderlineitemDescUpdatedAt.UpdateDefault.(func() time.Time)
}
