// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// OrderLineItem is the predicate function for orderlineitem builders.
type OrderLineItem func(*sql.Selector)
